### ISSUE TITLE
Images don't fill the whole view width

### ISSUE THREAD

**Issue by RLinV1** [UrbanProfessional/jsproject2#1]
Most images after the start of the game don't fil the whole viewport width

**Comment by RLinV1** [comment]
This is mainly because you set px width and height. Also each interactive item is used with a div that has a defined margin of px

**Comment by UrbanProfessional** [comment]
In Release 1.1 all of the backgrounds have been updated to support up to 1920 by 1080 pixel resolutions. This should fill the screens of most players. Since overflow is meant to be a gameplay feature, this will probably stay as is. Support for greater resolutions will be limited.
